baseurl = "http://bridgetdunnavantcscm.com/"
languageCode = "en-us"
title = "Centered Space, LLC – Counseling and Meditation"
theme = "bd-cscm"
canonifyurls = true

[params]
  name = "Bridget Dunnavant, PhD"
  creds = "Licensed Clinical Psychologist"
  description = "Offering counseling and meditation for anxiety, depression, LGBTQ and gender issues, fertility and family planning, grief- loss- and trauma- related reactions, and couples therapy."
  company = "Centered Space, LLC"
  tagline = "Counseling and Meditation"
  email = "Bridget.Dunnavant1@gmail.com"
  phone = "(804) 223 0626"