baseurl = "http://bridgetdunnavantcscm.com/"
canonifyurls = true
languageCode = "en-us"
theme = "bd-cscm"
title = "Centered Space, LLC – Counseling and Meditation"
[params]
company = "Centered Space, LLC"
creds = "Licensed Clinical Psychologist"
description = "Offering counseling and meditation for anxiety, depression, LGBTQ and gender issues, fertility and family planning, grief- loss- and trauma- related reactions, and couples therapy."
email = "Bridget.Dunnavant1@gmail.com"
hours = "Tuesdays, Thursdays, and Fridays 8am - 1pm"
name = "Bridget Dunnavant, PhD"
phone = "(804) 223 0626"
tagline = "Counseling and Meditation"
